#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Simple test"""
import requests

URL = "http://127.0.0.1:5000/links"

hj = requests.post(URL, json={"url": "https://about.estevao.xyz"})

print(hj.text)
